name: OdaTests Notifier

inputs:
  demos-run:
    description: "Number of demo tests that were run"
    required: true
  demos-passed:
    description: "The number of demo tests that passed"
    required: true
  discord-url:
    description: "Webhook url for discord"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout odatests-results branch
      uses: actions/checkout@v4
      with:
        ref: odatests-results
        path: ./odatests-results
    - name: Load previous run values
      id: previous
      shell: pwsh
      run: |
        $branchName = "${{ github.ref_name }}" -replace '/', '_'
        $jsonPath = "odatests-results\$branchName.json"
        if (Test-Path $jsonPath) {
          $jsonContent = Get-Content $jsonPath -Raw | ConvertFrom-Json
          echo "previous-total=$($jsonContent.demos_run)" >> $env:GITHUB_OUTPUT
          echo "previous-passes=$($jsonContent.demos_passed)" >> $env:GITHUB_OUTPUT
        } else {
          echo "previous-total=0" >> $env:GITHUB_OUTPUT
          echo "previous-passes=0" >> $env:GITHUB_OUTPUT
        }

    - name: Notify discord if values changed
      # if: steps.previous.outputs.previous-total != inputs.demos-run || steps.previous.outputs.previous-passes != inputs.demos-passed
      uses: tsickert/discord-webhook@v7.0.0
      with:
        webhook-url: ${{ inputs.discord-url }}
        embed-title: OdaTests Results Have Changed
        embed-url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        embed-color: 16711680
        embed-description: |
          **Branch:** `${{ github.ref_name }}`
          **Previous:** `${{ steps.previous.outputs.previous-passes }}/${{ steps.previous.outputs.previous-total }}`
          **Current:** `${{ inputs.demos-passed }}/${{ inputs.demos-run }}`

          🔗 [Commit](<${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}>)
          🔁 [Workflow Run](<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}>)

    - name: Write current run values
      shell: pwsh
      run: |
        $branchName = "${{ github.ref_name }}" -replace '/', '_'
        Set-Location odatests-results
        $jsonPath = "$branchName.json"
        $obj = @{
          demos_run = ${{ inputs.demos-run }}
          demos_passed = ${{ inputs.demos-passed }}
          updated_at = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
        }

        $jsonContent = $obj | ConvertTo-Json -Depth 3
        Set-Content -Path $jsonPath -Value $jsonContent -Encoding UTF8

        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"

        git add $jsonPath
        $commitMsg = "Update CI state for $branchName [ci skip]"
        git commit -m $commitMsg -a || Write-Host "No changes to commit"
        git push origin odatests-results